### ISSUE TITLE
Running the contributed command: 'changelog.generate' failed.

### ISSUE THREAD

**Issue by nickolboy** [axetroy/vscode-changelog-generator#119]
version: v1.0.4
vscode version: 1.55.2

Running the contributed command: 'changelog.generate' failed.

**Comment by nickolboy** [comment]
`Error: Command failed with exit code 1: D:\Microsoft VS Code\Code.exe c:\Users\Administrator\.vscode\extensions\axetroy.vscode-changelog-generator-1.0.4\node_modules\conventional-changelog-cli\cli.js --preset angular --release-count 0 --output-unreleasedexec: Unable to find a path to the node binary. Please manually set config.execPathTypeError: Cannot read property 'code' of null    at makeError (c:\Users\Administrator\.vscode\extensions\axetroy.vscode-changelog-generator-1.0.4\node_modules\execa\lib\error.js:59:11)    at handlePromise (c:\Users\Administrator\.vscode\extensions\axetroy.vscode-changelog-generator-1.0.4\node_modules\execa\index.js:114:26)    at runMicrotasks (<anonymous>)    at processTicksAndRejections (internal/process/task_queues.js:97:5)
m @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:35
_doInvokeHandler @ rpcProtocol.ts:417
_invokeHandler @ rpcProtocol.ts:402
_receiveRequest @ rpcProtocol.ts:318
_receiveOneMessage @ rpcProtocol.ts:245
(anonymous) @ rpcProtocol.ts:110
fire @ event.ts:622
fire @ ipc.net.ts:468
_receiveMessage @ ipc.net.ts:821
(anonymous) @ ipc.net.ts:660
fire @ event.ts:622
acceptChunk @ ipc.net.ts:241
(anonymous) @ ipc.net.ts:202
k @ ipc.net.ts:50
emit @ events.js:315
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:271
Readable.push @ _stream_readable.js:212
onStreamRead @ internal/stream_base_commons.js:186
`

**Comment by nickolboy** [comment]
`
Error: Command failed with exit code 1: D:\Microsoft VS Code\Code.exe c:\Users\Administrator\.vscode\extensions\axetroy.vscode-changelog-generator-1.0.4\node_modules\conventional-changelog-cli\cli.js --preset angular --release-count 0 --output-unreleasedexec: Unable to find a path to the node binary. Please manually set config.execPathTypeError: Cannot read property 'code' of null    at makeError (c:\Users\Administrator\.vscode\extensions\axetroy.vscode-changelog-generator-1.0.4\node_modules\execa\lib\error.js:59:11)    at handlePromise (c:\Users\Administrator\.vscode\extensions\axetroy.vscode-changelog-generator-1.0.4\node_modules\execa\index.js:114:26)    at runMicrotasks (<anonymous>)    at processTicksAndRejections (internal/process/task_queues.js:97:5)
m @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:35
_doInvokeHandler @ rpcProtocol.ts:417
_invokeHandler @ rpcProtocol.ts:402
_receiveRequest @ rpcProtocol.ts:318
_receiveOneMessage @ rpcProtocol.ts:245
(anonymous) @ rpcProtocol.ts:110
fire @ event.ts:622
fire @ ipc.net.ts:468
_receiveMessage @ ipc.net.ts:821
(anonymous) @ ipc.net.ts:660
fire @ event.ts:622
acceptChunk @ ipc.net.ts:241
(anonymous) @ ipc.net.ts:202
k @ ipc.net.ts:50
emit @ events.js:315
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:271
Readable.push @ _stream_readable.js:212
onStreamRead @ internal/stream_base_commons.js:186

`

**Comment by nickolboy** [comment]
Error: Command failed with exit code 1: D:\Microsoft VS Code\Code.exe c:\Users\Administrator\.vscode\extensions\axetroy.vscode-changelog-generator-1.0.4\node_modules\conventional-changelog-cli\cli.js --preset angular --release-count 0 --output-unreleasedexec: Unable to find a path to the node binary. Please manually set config.execPathTypeError: Cannot read property 'code' of null    at makeError (c:\Users\Administrator\.vscode\extensions\axetroy.vscode-changelog-generator-1.0.4\node_modules\execa\lib\error.js:59:11)    at handlePromise (c:\Users\Administrator\.vscode\extensions\axetroy.vscode-changelog-generator-1.0.4\node_modules\execa\index.js:114:26)    at runMicrotasks (<anonymous>)    at processTicksAndRejections (internal/process/task_queues.js:97:5)
m @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:35
_doInvokeHandler @ rpcProtocol.ts:417
_invokeHandler @ rpcProtocol.ts:402
_receiveRequest @ rpcProtocol.ts:318
_receiveOneMessage @ rpcProtocol.ts:245
(anonymous) @ rpcProtocol.ts:110
fire @ event.ts:622
fire @ ipc.net.ts:468
_receiveMessage @ ipc.net.ts:821
(anonymous) @ ipc.net.ts:660
fire @ event.ts:622
acceptChunk @ ipc.net.ts:241
(anonymous) @ ipc.net.ts:202
k @ ipc.net.ts:50
emit @ events.js:315
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:271
Readable.push @ _stream_readable.js:212
onStreamRead @ internal/stream_base_commons.js:186

**Comment by Ge-yuan-jun** [comment]
also have the problem

**Comment by avol-io** [comment]
also me

**Comment by Fucntion** [comment]
also me

**Comment by KeJunMao** [comment]
also me +1

**Comment by dmitryshelomanov** [comment]
+1 mac Big Sur

**Comment by eallion** [comment]
+1

**Comment by nickolboy** [comment]
只能先降到1.0.0版本

**Comment by christales** [comment]
`++`

**Comment by axetroy** [comment]
the extension has been deprecated. move to https://github.com/release-lab/vscode-whatchanged
