### ISSUE TITLE
Getting error in vscode

### ISSUE THREAD

**Issue by oleg-koval** [axetroy/vscode-changelog-generator#5]
Command failed: /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper /.vscode/extensions/axetroy.vscode-changelog-generator-0.4.0/node_modules/conventional-changelog-cli/cli.js --preset angular --release-count 0 internal/modules/cjs/loader.js:604 throw err; ^ Error: Cannot find module '/.vscode/extensions/axetroy.vscode-changelog-generator-0.4.0/node_modules/conventional-changelog-cli/cli.js' at Function.Module._resolveFilename (internal/modules/cjs/loader.js:602:15) at Function.Module._load (internal/modules/cjs/loader.js:528:25) at Function.Module.runMain (internal/modules/cjs/loader.js:753:10) at startup (internal/bootstrap/node.js:241:19) at bootstrapNodeJSCore (internal/bootstrap/node.js:579:3)

**Comment by Yaob1990** [comment]
Command failed: D:\Program Files\Microsoft VS Code\Code.exe c:\Users\Yao\.vscode\extensions\axetroy.vscode-changelog-generator-0.4.0\node_modules\conventional-changelog-cli\cli.js --preset angular --release-count 0 internal/modules/cjs/loader.js:604 throw err; ^ Error: Cannot find module 'c:\Users\Yao\.vscode\extensions\axetroy.vscode-changelog-generator-0.4.0\node_modules\conventional-changelog-cli\cli.js' at Function.Module._resolveFilename (internal/modules/cjs/loader.js:602:15) at Function.Module._load (internal/modules/cjs/loader.js:528:25) at Function.Module.runMain (internal/modules/cjs/loader.js:753:10) at startup (internal/bootstrap/node.js:241:19) at bootstrapNodeJSCore (internal/bootstrap/node.js:579:3)

i also have this problem

**Comment by axetroy** [comment]
thanks for the feedback.

This should be fixed in v0.4.1
